name: flutter_frame
description: "A high-performance, extensible Flutter framework with MVVM architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^13.2.1
  
  # Network
  dio: ^5.4.1
  connectivity_plus: ^5.0.2
  http: ^1.2.0
  internet_connection_checker: ^1.0.0+1
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  logger: ^2.0.2+1
  intl: ^0.20.2
  device_info_plus: ^9.1.2
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  
  # Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5

  sherpa_onnx: ^1.12.6
  record: ^6.0.0
  archive: ^4.0.7
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/res/
    - assets/config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
